version: 2
jobs:
  build:
    machine: true
        - run: git clone  https://github.com/MartinTopchyan/circleci-lib.git
        - run: cd circleci-lib
        - run: mvn clean install
#      working_directory: ~/projects
    steps:
      - checkout


#      - run: cd ..
#      - run: git clone https://github.com/MartinTopchyan/circleci-demo.git
#      - run: cd circleci-demo
#      - run: mvn package