version: 2
jobs:
  build:
    machine: true
#      working_directory: ~/projects
    steps:
      - checkout
      - restore_cache:
                key: circleci-lib-demo-{{ checksum "pom.xml" }}

            - run: mvn dependency:go-offline

            - save_cache:
                paths:
                  - ~/.m2
                key: circleci-circleci-lib-demo-{{ checksum "pom.xml" }}

      - run: mvn package