version: 2
jobs:
  build:
    machine: true
#      working_directory: ~/projects
    steps:
      - checkout
      - run: git clone  https://github.com/MartinTopchyan/circleci-lib.git

      - run: mvn package